# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Rants
email:       'luis@luispuerto.net'
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://rants.luispuerto.net/' # The base hostname & protocol for your site
twitter:     'lpuerto'
github:      'luispuerto'

markdown:  kramdown
permalink: pretty
paginate:  10
timezone: UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jemoji

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
      comments: false
  - scope: 
      path: ''
      type: posts
    values: 
      comments: true 
